### ISSUE TITLE
Getting Started steps say to import a different repo

### ISSUE THREAD

**Issue by mrcarter8** [Azure-Samples/azure-search-performance-testing#1]
Step 1 of the Getting Started guidance says to import a different repo: https://github.com/ignaciofls/LoadTest-AzureCognitiveSearch-Jmeter-Terraform

It seems like this is incorrect and I'm wondering if this is from when the repro was somewhere else.  I would expect it to be this repo: https://github.com/Azure-Samples/azure-search-performance-testing

**Comment by dereklegenzoff** [comment]
Thanks for flagging this! The repo has now been updated
